management:
  endpoints:
    web:
      base-path: /private
      exposure:
        include: prometheus
        exclude: metrics
      path-mapping:
        prometheus: metrics

spring:
  datasource:
    url: 'jdbc:h2:mem:branches'
    driverClassName: 'org.h2.Driver'
    username: 'dbtrips'
    password: ''
  jpa:
    database-platform: 'org.hibernate.dialect.H2Dialect'
    hibernate:
      ddl-auto: 'create'
    show-sql: true
  h2:
    console:
      enabled: true
      path: '/h2-console'
      settings:
        web-allow-others: true

server:
  servlet:
    context-path: /uber-trips
  tomcat:
    accept-count: 120
    mbeanregistry:
      enabled: true
    threads:
      max: 1200

service:
  database:
    embedded: true
